### ISSUE TITLE
Uninstalling fails to remove access key from database; connection broken after upgrade

### ISSUE THREAD

**Issue by freeform-sg** [veda-consulting/uk.co.vedaconsulting.gotowebinar#26] opened 2016-05-02 21:25 UTC
Hi there, we upgraded to the latest version but afterwards the settings page showed a "InvalidToken    Invalid token passed", but did not present the fields to re-enter the username and password, therefor the connection could not be reestablished. 

After uninstalling hoping that a full re-install would fix the issue, we found that nothing was removed from the database and therefor the problem persisted.

We reviewed /CRM/Gotowebinar/Form/Settings.php and found that the display of the form fields was solely dependent on "if($accessToken && $organizerKey)", unfortunately this conditional ignores whether you have a valid connection or not - perhaps the logic could be altered here? It also assumes you never want to change which account you connect to, which is problematic.

To 'trick' the system into letting us re-connect, we followed the code to find where $accessToken was defined: in the table civicrm_setting, delete the entry where group_name = "Webinar Preferences", and name = "access_token".

**Comment by Kajakaran** [comment] 2016-05-03 15:45
@freeform-sg 

Yes. You are right. I think this situation happened because your access_token expired?
We have to have access token expiry information in setting page so that if access token is going to expire, then we could notify user in the setting page and get new access token from GoToWebinar.

Also we have to remove access_token from setting table when the extension is uninstalled.

Are you able to do a PR for above?

Thanks

**Comment by freeform-sg** [comment] 2016-05-03 18:00
@Kajakaran I'm not entirely sure the token expired, or how to tell if that is the case - I unfortunately didn't have the time to try and replicate the error by going through the upgrade process on a clean site. The client tried to upgrade to 1.6.2 from 1.5 and that's when the issue arose, so I wonder if it was a matter of the access token getting corrupt, I really don't know. (I'm also not entirely sure how the access tokens are created, I didn't dive that far into the code.)

Regardless, folks should be able to enter new credentials whenever they want, so why not remove the clause that limits the display of the form items? Or would that cause issues?

The access token isn't the only item in the database, there are two tables that belong to the extension as well - deleting them would remove all the info that links CiviCRM content to webinars, but that would be expected in an uninstall.

**Comment by Kajakaran** [comment] 2016-05-04 15:25
@freeform-sg 

Thanks for your comments.

We need to clean-up on uninstall whatever the changes done to database.

Regardless, folks should be able to enter new credentials whenever they want, so why not remove the clause that limits the display of the form items? Or would that cause issues?

This might cause problem if we remove the clause because user would be able to connect GoToWebinar with their same user credentials and every time they connect to GoToWebinar, user will get new access token. This is not expected behaviour.

**Comment by freeform-sg** [comment] 2016-05-04 16:54
@Kajakaran 

Thanks for clarifying how the access token works. Sounds like within "if($accessToken && $organizerKey)" we could use a check for if the access token is valid (or connection successful).

**Comment by veda-consulting** [comment] 2017-10-13 12:28
@freeform-sg we've now included a fix for this, detecting if Tokens have expired and prompting for a new one in the settings page. Please see v2.0.0

**Closed by veda-consulting** 2017-10-13 12:28 UTC

**Comment by freeform-sg** [comment] 2017-10-13 13:55
Thank you for this! I'd completely forgotten about this issue - I will let
my clients know.




Stephanie Gray <stephanie@freeform.ca>, Web Developer
Freeform Solutions <http://www.freeform.ca/> - 647.723.5415 x109

A nonprofit that helps mission-driven organizations connect to their world.
